### ISSUE TITLE
Will not authenticate - new MyCourses Auth

### ISSUE THREAD

**Issue by kocsenc** [volfco/MyCoursesDownloader#10]
MyCourses now uses RIT's authentication system; which means this one wont work :(.

**Comment by volfco** [comment]
Yeah, I know. I have the code to get around it, I just need to implement.

**Comment by volfco** [comment]
Quick Update. I'm digging into the issue. D2l is using more/different security then ITS here at RIT does, so I have to dig deeper into the process to figure this out. No quick fixes here.

**Comment by volfco** [comment]
Fixed and verified as working. Closing this issue.
