### ISSUE TITLE
Bug in commit: ab04f4e9aa360bbf3c56d1f5c54962ea1711564f

### ISSUE THREAD

**Issue by dustin-decker** [volfco/MyCoursesDownloader#4]
`Downloading contents
Traceback (most recent call last):
  File "mycoursesdownloader.py", line 180, in <module>
    if not os.path.isdir(safeFilePath(path)):
  File "mycoursesdownloader.py", line 44, in safeFilePath
    path = path.decode('unicode_escape').encode('ascii', 'ignore')
AttributeError: 'str' object has no attribute 'decode'`

Verified on Ubuntu 14.10 (python3.4 in repository) and Windows 8.1 (https://www.python.org/ftp/python/3.4.3/python-3.4.3.amd64.msi) with latest pip packages for dependencies.

**Comment by volfco** [comment]
Oops. Thanks. Fixed.
