### ISSUE TITLE
Print "Downloading <item_name>" fails on Unicode character

### ISSUE THREAD

**Issue by brianto** [volfco/MyCoursesDownloader#6]
See [PrintFails](https://wiki.python.org/moin/PrintFails).

```
Traceback (most recent call last):
  File ".\mycoursesdownloader.py", line 262, in <module>
    print("   Downloading " + dropbox_item_name)
  File "C:\Python33\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2013' in position 40: character maps to <undefined>
```

Perhaps use [`str.encode`](https://docs.python.org/3/library/stdtypes.html#str.encode)? [Reference](http://code.activestate.com/recipes/576602-safe-print/).

**Comment by volfco** [comment]
Just pushed a fix. I had a function to strip unicode, but it was not being run on the print statements. Now it is.

**Comment by brianto** [comment]
:+1: Thanks, dude!
